apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-nextjs-markdown
  name: demo-nextjs-markdown-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: demo-nextjs-markdown
  template:
    metadata:
      labels:
        app: demo-nextjs-markdown
    spec:
      containers:
        - name: demo-nextjs-markdown
          image: asia.gcr.io/PROJECT_ID/IMAGE:TAG
          # COMMENT TO NOT EXPOSING THE PORT OUTSIDE THE POD
          ports:
            - containerPort: 3000
          resources: {}
          command:
            [
              'pm2-runtime',
              'start',
              'yarn',
              '--interpreter',
              'sh',
              '--name',
              'demo-nextjs-markdown',
              '--',
              'start',
            ]
      restartPolicy: Always
status: {}
