version: '3.8'
services:
  demo-nextjs-markdown:
    # @NOTE - AVOID USING "latest" TAG IN K8S YML CONFIG - https://kubernetes.io/docs/concepts/containers/images/
    image: knkevinlai/demo-nextjs-markdown:${BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: demo-nextjs-markdown
    ports:
      - "${PORT:-3000}:3000"
    entrypoint:
      [
        "pm2-runtime",
        "start",
        "yarn",
        "--interpreter",
        "sh",
        "--name",
        "demo-nextjs-markdown",
        "--",
        "start"
      ]
