kind: Service
apiVersion: v1
metadata:
  name: demo-nextjs-markdown-service
  annotations:
    networking.gke.io/load-balancer-type: 'Internal'
spec:
  selector:
    app: demo-nextjs-markdown
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8666
      targetPort: 3000
